name: flutter_clean_architecture
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  http: ^0.13.3
  rxdart: ^0.27.3
  google_fonts: ^2.1.0
  shimmer: ^2.0.0
  intl: ^0.17.0
  # tuple: ^2.0.0
  provider: ^6.0.2
  dio: ^4.0.6
  http_mock_adapter: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  bloc_test: ^9.0.2
  build_runner: ^2.1.2
  mockito: ^5.0.15
  mocktail: ^0.2.0   

flutter:
  uses-material-design: true
  assets:
    - assets/images/
