// Mocks generated by Mockito 5.2.0 from annotations
// in flutter_clean_architecture/test/helpers/test_helper.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;
import 'dart:convert' as _i10;
import 'dart:typed_data' as _i11;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_clean_architecture/core/failure.dart' as _i6;
import 'package:flutter_clean_architecture/data/data_sources/movies_remote_data_souce.dart'
    as _i8;
import 'package:flutter_clean_architecture/domain/entities/movie.dart' as _i7;
import 'package:flutter_clean_architecture/domain/repositories/movies_repository.dart'
    as _i3;
import 'package:flutter_clean_architecture/domain/usecases/get_search_movie_list.dart'
    as _i9;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

class _FakeTuple2_1<T1, T2> extends _i1.Fake implements _i2.Tuple2<T1, T2> {}

class _FakeMoviesRepository_2 extends _i1.Fake implements _i3.MoviesRepository {
}

class _FakeResponse_3 extends _i1.Fake implements _i4.Response {}

class _FakeStreamedResponse_4 extends _i1.Fake implements _i4.StreamedResponse {
}

/// A class which mocks [MoviesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoviesRepository extends _i1.Mock implements _i3.MoviesRepository {
  MockMoviesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i2.Tuple2<List<_i7.Movie>, int>>>
      getSearchMovieList({String? query, int? page}) => (super.noSuchMethod(
          Invocation.method(
              #getSearchMovieList, [], {#query: query, #page: page}),
          returnValue:
              Future<_i2.Either<_i6.Failure, _i2.Tuple2<List<_i7.Movie>, int>>>.value(
                  _FakeEither_0<_i6.Failure, _i2.Tuple2<List<_i7.Movie>, int>>())) as _i5
          .Future<_i2.Either<_i6.Failure, _i2.Tuple2<List<_i7.Movie>, int>>>);
}

/// A class which mocks [MoviesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoviesRemoteDataSource extends _i1.Mock
    implements _i8.MoviesRemoteDataSource {
  MockMoviesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Tuple2<List<_i7.Movie>, int>> getMovieList(
          {String? query, int? page}) =>
      (super.noSuchMethod(
          Invocation.method(#getMovieList, [], {#query: query, #page: page}),
          returnValue: Future<_i2.Tuple2<List<_i7.Movie>, int>>.value(
              _FakeTuple2_1<List<_i7.Movie>, int>())) as _i5
          .Future<_i2.Tuple2<List<_i7.Movie>, int>>);
}

/// A class which mocks [GetSearchMovieList].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSearchMovieList extends _i1.Mock
    implements _i9.GetSearchMovieList {
  MockGetSearchMovieList() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.MoviesRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMoviesRepository_2()) as _i3.MoviesRepository);
  @override
  _i5.Future<_i2.Either<_i6.Failure, _i2.Tuple2<List<_i7.Movie>, int>>> call(
          {String? query, int? page}) =>
      (super.noSuchMethod(
          Invocation.method(#call, [], {#query: query, #page: page}),
          returnValue:
              Future<_i2.Either<_i6.Failure, _i2.Tuple2<List<_i7.Movie>, int>>>.value(
                  _FakeEither_0<_i6.Failure,
                      _i2.Tuple2<List<_i7.Movie>, int>>())) as _i5
          .Future<_i2.Either<_i6.Failure, _i2.Tuple2<List<_i7.Movie>, int>>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i4.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i4.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: Future<_i4.Response>.value(_FakeResponse_3()))
          as _i5.Future<_i4.Response>);
  @override
  _i5.Future<_i4.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: Future<_i4.Response>.value(_FakeResponse_3()))
          as _i5.Future<_i4.Response>);
  @override
  _i5.Future<_i4.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i10.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i4.Response>.value(_FakeResponse_3()))
          as _i5.Future<_i4.Response>);
  @override
  _i5.Future<_i4.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i10.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i4.Response>.value(_FakeResponse_3()))
          as _i5.Future<_i4.Response>);
  @override
  _i5.Future<_i4.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i10.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i4.Response>.value(_FakeResponse_3()))
          as _i5.Future<_i4.Response>);
  @override
  _i5.Future<_i4.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i10.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i4.Response>.value(_FakeResponse_3()))
          as _i5.Future<_i4.Response>);
  @override
  _i5.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: Future<String>.value('')) as _i5.Future<String>);
  @override
  _i5.Future<_i11.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: Future<_i11.Uint8List>.value(_i11.Uint8List(0)))
          as _i5.Future<_i11.Uint8List>);
  @override
  _i5.Future<_i4.StreamedResponse> send(_i4.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue:
                  Future<_i4.StreamedResponse>.value(_FakeStreamedResponse_4()))
          as _i5.Future<_i4.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
}
